--------------------------------------------------------
--  File created - вторник-Февраль-14-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EXAMS
--------------------------------------------------------

  CREATE TABLE "C##BD_LESHA"."EXAMS" 
   (	"LESSONS_NAME" VARCHAR2(30 BYTE), 
	"TEACHER_ID" VARCHAR2(30 BYTE), 
	"STUDENTS_GROUP" VARCHAR2(30 BYTE), 
	"FACULTY_NAME" VARCHAR2(30 BYTE), 
	"ROOM_NUMBER" VARCHAR2(30 BYTE), 
	"EXAM_DATE" VARCHAR2(30 BYTE), 
	"EXAM_TIME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LESSONS
--------------------------------------------------------

  CREATE TABLE "C##BD_LESHA"."LESSONS" 
   (	"LESSONS_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MARKS
--------------------------------------------------------

  CREATE TABLE "C##BD_LESHA"."MARKS" 
   (	"STUDENT_PASSPORT" VARCHAR2(30 BYTE), 
	"TEACHER_PASSPORT" VARCHAR2(30 BYTE), 
	"LESSON_NAME" VARCHAR2(30 BYTE), 
	"LESSON_MARK" VARCHAR2(30 BYTE), 
	"STUDENT_GROUP" VARCHAR2(30 BYTE), 
	"EXAM_DATE" VARCHAR2(30 BYTE), 
	"STUDENT_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

  CREATE TABLE "C##BD_LESHA"."STUDENTS" 
   (	"USER_PASSPORT" VARCHAR2(30 BYTE), 
	"USER_UNIVERSITY" VARCHAR2(30 BYTE), 
	"USER_FACULTY" VARCHAR2(30 BYTE), 
	"USER_COURSE" NUMBER, 
	"USER_GROUP" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEACHERLESSONS
--------------------------------------------------------

  CREATE TABLE "C##BD_LESHA"."TEACHERLESSONS" 
   (	"TEACHER_PASSPORT" VARCHAR2(30 BYTE), 
	"LESSONS_NAME" VARCHAR2(30 BYTE), 
	"STUDENTS_GROUP" VARCHAR2(30 BYTE), 
	"STUDENTS_COURSE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEACHERS
--------------------------------------------------------

  CREATE TABLE "C##BD_LESHA"."TEACHERS" 
   (	"USER_PASSPORT" VARCHAR2(20 BYTE), 
	"UNIVERSITY_ADDRESS" VARCHAR2(20 BYTE), 
	"USER_FACULTY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UNIVERSITY
--------------------------------------------------------

  CREATE TABLE "C##BD_LESHA"."UNIVERSITY" 
   (	"UNIVERSITY_NAME" VARCHAR2(30 BYTE), 
	"UNIVERSITY_ADDRESS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##BD_LESHA"."USERS" 
   (	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_SURNAME" VARCHAR2(30 BYTE), 
	"USER_PASSPORT" VARCHAR2(30 BYTE), 
	"USER_PASS" VARCHAR2(30 BYTE), 
	"USER_TYPE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERSTYPE
--------------------------------------------------------

  CREATE TABLE "C##BD_LESHA"."USERSTYPE" 
   (	"USER_TYPE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010513
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BD_LESHA"."SYS_C0010513" ON "C##BD_LESHA"."LESSONS" ("LESSONS_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TEACHERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BD_LESHA"."TEACHERS_PK" ON "C##BD_LESHA"."TEACHERS" ("USER_PASSPORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010500
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BD_LESHA"."SYS_C0010500" ON "C##BD_LESHA"."UNIVERSITY" ("UNIVERSITY_ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010477
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BD_LESHA"."SYS_C0010477" ON "C##BD_LESHA"."USERS" ("USER_PASSPORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010482
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BD_LESHA"."SYS_C0010482" ON "C##BD_LESHA"."USERSTYPE" ("USER_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EXAMS
--------------------------------------------------------

  ALTER TABLE "C##BD_LESHA"."EXAMS" MODIFY ("LESSONS_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."EXAMS" MODIFY ("TEACHER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."EXAMS" MODIFY ("STUDENTS_GROUP" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."EXAMS" MODIFY ("FACULTY_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."EXAMS" MODIFY ("ROOM_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."EXAMS" MODIFY ("EXAM_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."EXAMS" MODIFY ("EXAM_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LESSONS
--------------------------------------------------------

  ALTER TABLE "C##BD_LESHA"."LESSONS" ADD PRIMARY KEY ("LESSONS_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MARKS
--------------------------------------------------------

  ALTER TABLE "C##BD_LESHA"."MARKS" MODIFY ("STUDENT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "C##BD_LESHA"."STUDENTS" MODIFY ("USER_UNIVERSITY" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."STUDENTS" MODIFY ("USER_FACULTY" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."STUDENTS" MODIFY ("USER_COURSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEACHERLESSONS
--------------------------------------------------------

  ALTER TABLE "C##BD_LESHA"."TEACHERLESSONS" MODIFY ("TEACHER_PASSPORT" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."TEACHERLESSONS" MODIFY ("LESSONS_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."TEACHERLESSONS" MODIFY ("STUDENTS_GROUP" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."TEACHERLESSONS" MODIFY ("STUDENTS_COURSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEACHERS
--------------------------------------------------------

  ALTER TABLE "C##BD_LESHA"."TEACHERS" MODIFY ("USER_PASSPORT" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."TEACHERS" MODIFY ("UNIVERSITY_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."TEACHERS" MODIFY ("USER_FACULTY" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."TEACHERS" ADD CONSTRAINT "TEACHERS_PK" PRIMARY KEY ("USER_PASSPORT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UNIVERSITY
--------------------------------------------------------

  ALTER TABLE "C##BD_LESHA"."UNIVERSITY" MODIFY ("UNIVERSITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."UNIVERSITY" ADD PRIMARY KEY ("UNIVERSITY_ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##BD_LESHA"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."USERS" MODIFY ("USER_SURNAME" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."USERS" MODIFY ("USER_PASSPORT" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."USERS" MODIFY ("USER_PASS" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."USERS" ADD PRIMARY KEY ("USER_PASSPORT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##BD_LESHA"."USERS" MODIFY ("USER_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERSTYPE
--------------------------------------------------------

  ALTER TABLE "C##BD_LESHA"."USERSTYPE" MODIFY ("USER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##BD_LESHA"."USERSTYPE" ADD PRIMARY KEY ("USER_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
